### ISSUE TITLE
Request: Add example for embedded device, like ESP32 or STM32

### ISSUE THREAD

**Issue by DeflateAwning** [eldruin/lm75-rs#2]

**Comment by eldruin** [comment]
There are examples in the [driver-examples](https://github.com/eldruin/driver-examples) repository (linked in the readme) for an STM32F103 and an STM32F303.
If you have further questions, feel free to reopen.

**Comment by DeflateAwning** [comment]
Awesome; I sitll can't figure out how to make it work with the ESP32 I2C driver.

It would be awesome to add links to these examples in the README:
* https://github.com/eldruin/driver-examples/blob/master/stm32f1-bluepill/examples/lm75-temp-display-bp.rs
* https://github.com/eldruin/driver-examples/blob/master/stm32f3-discovery/examples/lm75-usart-f3.rs
